apiVersion: rbac.authorization.k8s.io/v1betal
kind: ClusterRoleBinding
metadata:
 name: nfs-provisioner-role-binding
subjects:
  - kind: ServiceAccount
     name: default
     namespace: lwns
roleRef:
  kind: ClusterRole
  name: Cluster-admin
  apiGroup: rbac.authorization.k8s.io